"""Table_update_user_1

Revision ID: 567581874fdb
Revises: 346244c96eb2
Create Date: 2026-01-08 23:30:23.971384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


user_roles_enum = ENUM(
    "customer",
    "owner",
    name="user_roles_enum"
)


# revision identifiers, used by Alembic.
revision: str = '567581874fdb'
down_revision: Union[str, Sequence[str], None] = '346244c96eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # user_roles_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('mobile', sa.String(length=10), nullable=False),
    sa.Column('role', sa.Enum('customer', 'owner', name='user_roles_enum'), server_default='customer', nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_loggedin', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_check_constraint(
        "ck_users_mobile_10_digits",
        "users",
        "mobile ~ '^[0-9]{10}$'"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_roles_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_table('users')
    op.drop_constraint(
        "ck_users_mobile_10_digits",
        "users",
        type_="check"
    )
    # ### end Alembic commands ###
