"""table_new_otp1

Revision ID: 6a3d773e0d23
Revises: 567581874fdb
Create Date: 2026-01-09 16:55:47.241146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3d773e0d23'
down_revision: Union[str, Sequence[str], None] = '567581874fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('mobile', sa.String(length=10), nullable=False),
    sa.Column('otp', sa.String(length=4), nullable=False),
    sa.Column('expiry_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otp')
    # ### end Alembic commands ###
